apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: azure-csi-provider
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-06-10T18:14:32Z"
  generation: 1
  labels:
    app: csi-secrets-store-provider-azure
    app.kubernetes.io/instance: azure-csi-provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-secrets-store-provider-azure
    app.kubernetes.io/version: 1.0.1
    helm.sh/chart: csi-secrets-store-provider-azure-1.0.1
  name: azure-csi-provider-csi-secrets-store-provider-azure
  namespace: kube-system
  resourceVersion: "304218"
  uid: 2dad0022-be5f-4494-b6eb-38fb27a60a27
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-secrets-store-provider-azure
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-secrets-store-provider-azure
        app.kubernetes.io/instance: azure-csi-provider
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: csi-secrets-store-provider-azure
        app.kubernetes.io/version: 1.0.1
        helm.sh/chart: csi-secrets-store-provider-azure-1.0.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      containers:
      - args:
        - --endpoint=unix:///provider/azure.sock
        - --construct-pem-chain=true
        - --healthz-port=8989
        - --healthz-path=/healthz
        - --healthz-timeout=5s
        image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8989
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: provider-azure-installer
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /provider
          name: provider-vol
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: csi-secrets-store-provider-azure
      serviceAccountName: csi-secrets-store-provider-azure
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/secrets-store-csi-providers
          type: ""
        name: provider-vol
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 1
  updatedNumberScheduled: 3
