apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-secrets-store-inline
  namespace: kube-system
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: busybox
          image: k8s.gcr.io/e2e-test-images/busybox:1.29
          command:
            - "/bin/sleep"
            - "10000"
          env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: test
                key: test       
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/etc/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:
              name: secrets-store-creds
