apiVersion: v1
items:
- apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:
    name: azure-kvname
    namespace: my-application
  spec:
    parameters:
      keyvaultName: secret-store-yxsQD06s2K                    # The name of the Keyvault
      objects: |
        array:
          - |
            objectName: secret1
            objectType: secret
            objectVersion: ""
          - |
            objectName: username
            objectType: secret                                 # Setting the objectType to secret will retrieve the certificate and private key from keyvault.
            objectVersion: ""
      tenantId: 64dc69e4-d083-49fc-9569-ebece1dd1408           # The tenant ID of KeyVault
      usePodIdentity: "false"
      useVMManagedIdentity: "false"
      userAssignedIdentityID: ""
    provider: azure
    secretObjects:                                             # secretObjects defines the desired state of synced K8s secret objects
    - data:
      - key: suresh
        objectName: username
      secretName: appcred
      type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
